### ISSUE TITLE
Webtop for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [k0gen/webtop-startos#4]
### Service: Webtop
This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched.

**Current Status:**
- [ ] Works Fine
- [ ] Partial Issues
- [x] Doesn't Work

**Description:**
The Webtop service is experiencing healthcheck issues in StartOS 0.3.6.

**Tasks:**
- [ ] Investigate and identify the root cause of the healthcheck issues.
- [ ] Implement fixes to ensure reliable healthcheck results.
- [ ] Verify that the Webtop service performs consistently under various conditions.
- [ ] Ensure all features of Webtop are tested and functioning as expected.

**Comment by k0gen** [comment]
### Health checks issue:

```
 Webtop Interface
Error while fetching URL: http://webtop.embassy:3000 
```

Logs

```
2024-08-08T08:51:50+02:00  [i] Initialising Webtop ...
2024-08-08T08:51:50+02:00  s6-overlay-suexec: fatal: can only run as pid 1
2024-08-08T08:51:50+02:00  Error: docker_entrypoint.sh exited with code 100
2024-08-08T08:51:50+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-08T08:51:50+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-08T08:51:50+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-08-08T08:51:50+02:00  Filesystem I/O Error: No such file or directory (os error 2)
2024-08-08T08:51:50+02:00  Error: docker_entrypoint.sh exited with code 2
2024-08-08T08:51:50+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-08T08:51:50+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-08T08:51:50+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-08-08T08:52:05+02:00  Error while fetching URL: http://webtop.embassy:3000
```
